const constants = {
  SUPER_STORE: '@SUPER_STORE:key',
  PALESTRA: 'PALESTRA',
  ABERTURA: 'ABERTURA',
  CHECKIN: 'CHECKIN',
  COFFEE_BREAK: 'COFFEE-BREAK',
  CORRIDA_ROBOS: 'CORRIDA-ROBOS',
  MARATONA_PROGRAMACAO: 'MARATONA-PROGRAMACAO',
  DE_ALUNO_PARA_ALUNO: 'DE-ALUNO-PARA-ALUNO',
  EMPRESA: 'EMPRESA',
  GAMEDAY: 'GAMEDAY',
  MINICURSO: 'MINICURSO',
  LABORATORIO: 'LABORATORIO',
  COORDENACAO: 'COORDENACAO',
  CENTRO_ACADEMICO: 'CENTRO-ACADEMICO',
};

export default constants;