export const MUDA_NOME_LOGIN = 'MUDA_NOME_LOGIN';
export const MUDA_CURSO_LOGIN = 'MUDA_CURSO_LOGIN';
export const MUDA_EMAIL_LOGIN = 'MUDA_EMAIL_LOGIN';
export const MUDA_SENHA_LOGIN = 'MUDA_SENHA_LOGIN';
export const MUDA_FERA_LOGIN = 'MUDA_FERA_LOGIN';
export const MUDA_EH_INSCRICAO = 'MUDA_EH_INSCRICAO';